site_name: xrun
repo_name: xrun

repo_url: https://github.com/heroesofcode/xrun
site_url: https://heroesofcode.github.io/xrun
docs_dir: 'docs'
edit_uri: 'tree/master/docs/'

extra:
  manifest: manifest.webmanifest
  site:
    images: '../../images'
  xrun:
    release: "0.11.0"
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/heroesofcode'
    - icon: fontawesome/solid/arrow-up-right-from-square
      link: 'https://heroesofcode.com'
theme:
  name: 'material'
  language: en
  custom_dir: 'docs/theme'
  font:
    text: Ubuntu
    code: Jetbrains Mono
  features:
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.share
  palette:
    - scheme: default
      primary: deep-blue
      accent: deep-purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    logo: fontawesome/solid/code
    repo: fontawesome/brands/github
nav:
  - Overview: index.md
  - Installation: installation.md
  - How to use?: howtouse.md
  - Github Actions: githubaction.md
  - Changelog: changelog.md
  - License: license.md
markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji
  - tables
  - admonition

plugins:
  - search
  - macros
  - git-revision-date-localized:
      type: date
