site_name: "xrun"
theme:
  name: "material"
  palette:
    primary: 'blue'
    accent: 'light blue'
  features:
    - navigation.instant

nav:
  - Overview: index.md
  - Changelog: changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/heroesofcode/xrun
