name: CI
on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-26

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Mise install
        uses: jdx/mise-action@0409dde834f41cd7d184340824f5557970508db8
        with:
          cache: true
          experimental: true

      - uses: Swatinem/rust-cache@f51f967e158417aafa338a1e46ab22095f07aa01

      - name: Read Xcode version
        id: xcode_version
        run: echo "XCODE_VERSION=$(cat .xcode-version)" >> $GITHUB_ENV

      - name: Setup Xcode using .xcode-version
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Build
        run: mise build

      - name: Run iOS example
        run: mise ios

      - name: Run tests
        run: mise test
