name: CI
on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-26

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Mise install
        uses: jdx/mise-action@c1ecc8f748cd28cdeabf76dab3cccde4ce692fe4
        with:
          cache: true
          experimental: true

      - uses: Swatinem/rust-cache@bc1860267c1b189716ecde249f61cf86e8408d91

      - name: Read Xcode version
        id: xcode_version
        run: echo "XCODE_VERSION=$(cat .xcode-version)" >> $GITHUB_ENV

      - name: Setup Xcode using .xcode-version
        uses: maxim-lobanov/setup-xcode@7f352e61cbe8130c957c3bc898c4fb025784ea1e
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Build
        run: mise build

      - name: Run iOS example
        run: mise ios

      - name: Run tests
        run: mise test
